apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-apache
  name: web-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-apache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-apache
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
